const components = [
  // opening — four genuinely different entrance interactions, not recolors
  {
    component_id: "opening_curtain",
    section: "opening",
    name: "Sliding Curtain",
    preview_bg_color: "#7c2d3a",
    preview_text_color: "#ffffff",
    preview_accent_color: "#d4af37",
    font_style: "serif",
  },
  {
    component_id: "opening_door",
    section: "opening",
    name: "Double Doors",
    preview_bg_color: "#3a2e2e",
    preview_text_color: "#ffffff",
    preview_accent_color: "#c9a35c",
    font_style: "serif",
  },
  {
    component_id: "opening_book",
    section: "opening",
    name: "Book Cover",
    preview_bg_color: "#2f3e46",
    preview_text_color: "#ffffff",
    preview_accent_color: "#cad2c5",
    font_style: "serif",
  },
  {
    component_id: "opening_envelope",
    section: "opening",
    name: "Envelope",
    preview_bg_color: "#fff8f5",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "serif",
  },
  // one default component per remaining section for v1 — more variants later, on demand
  {
    component_id: "hero_classic",
    section: "hero",
    name: "Classic",
    preview_bg_color: "#fff8f5",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "serif",
  },
  {
    component_id: "story_classic",
    section: "story",
    name: "Classic",
    preview_bg_color: "#ffffff",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "serif",
  },
  {
    component_id: "gallery_grid",
    section: "gallery",
    name: "Grid",
    preview_bg_color: "#ffffff",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "sans",
  },
  {
    component_id: "details_classic",
    section: "details",
    name: "Classic",
    preview_bg_color: "#fff8f5",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "serif",
  },
  {
    component_id: "rsvp_classic",
    section: "rsvp",
    name: "Classic",
    preview_bg_color: "#ffffff",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "sans",
  },
  {
    component_id: "registry_classic",
    section: "registry",
    name: "Classic",
    preview_bg_color: "#ffffff",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "sans",
  },
  {
    component_id: "timeline_classic",
    section: "timeline",
    name: "Classic",
    preview_bg_color: "#fff8f5",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "serif",
  },
  {
    component_id: "music_classic",
    section: "music",
    name: "Classic",
    preview_bg_color: "#ffffff",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "sans",
  },
];

export default {
  section_components: components.map((c) => ({ ...c, status: "active" })),
};
