const components = [
  // opening — four genuinely different entrance interactions, not recolors
  {
    component_id: "opening_curtain",
    section: "opening",
    name: "Sliding Curtain",
    preview_bg_color: "#7c2d3a",
    preview_text_color: "#ffffff",
    preview_accent_color: "#d4af37",
    font_style: "serif",
  },
  {
    component_id: "opening_door",
    section: "opening",
    name: "Double Doors",
    preview_bg_color: "#3a2e2e",
    preview_text_color: "#ffffff",
    preview_accent_color: "#c9a35c",
    font_style: "serif",
  },
  {
    component_id: "opening_book",
    section: "opening",
    name: "Book Cover",
    preview_bg_color: "#2f3e46",
    preview_text_color: "#ffffff",
    preview_accent_color: "#cad2c5",
    font_style: "serif",
  },
  {
    component_id: "opening_envelope",
    section: "opening",
    name: "Envelope",
    preview_bg_color: "#fff8f5",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "serif",
  },
  // hero — three genuinely different layouts
  {
    component_id: "hero_classic",
    section: "hero",
    name: "Classic",
    preview_bg_color: "#fff8f5",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "serif",
  },
  {
    component_id: "hero_polaroid",
    section: "hero",
    name: "Polaroid",
    preview_bg_color: "#fffaf3",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#b98b4e",
    font_style: "serif",
  },
  {
    component_id: "hero_fullbleed",
    section: "hero",
    name: "Full Bleed",
    preview_bg_color: "#1f1b18",
    preview_text_color: "#ffffff",
    preview_accent_color: "#c9a35c",
    font_style: "sans",
  },
  // story
  {
    component_id: "story_classic",
    section: "story",
    name: "Classic",
    preview_bg_color: "#ffffff",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "serif",
  },
  {
    component_id: "story_letter",
    section: "story",
    name: "Letter",
    preview_bg_color: "#fff8f0",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#a9793f",
    font_style: "serif",
  },
  {
    component_id: "story_split",
    section: "story",
    name: "Split",
    preview_bg_color: "#ffffff",
    preview_text_color: "#2f2a26",
    preview_accent_color: "#c9a35c",
    font_style: "sans",
  },
  // gallery
  {
    component_id: "gallery_grid",
    section: "gallery",
    name: "Grid",
    preview_bg_color: "#ffffff",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "sans",
  },
  {
    component_id: "gallery_masonry",
    section: "gallery",
    name: "Masonry",
    preview_bg_color: "#ffffff",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "sans",
  },
  {
    component_id: "gallery_carousel",
    section: "gallery",
    name: "Carousel",
    preview_bg_color: "#ffffff",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "sans",
  },
  // details
  {
    component_id: "details_classic",
    section: "details",
    name: "Classic",
    preview_bg_color: "#fff8f5",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "serif",
  },
  {
    component_id: "details_split",
    section: "details",
    name: "Split",
    preview_bg_color: "#fff8f5",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "serif",
  },
  {
    component_id: "details_cards",
    section: "details",
    name: "Cards",
    preview_bg_color: "#ffffff",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "sans",
  },
  // rsvp
  {
    component_id: "rsvp_classic",
    section: "rsvp",
    name: "Classic",
    preview_bg_color: "#ffffff",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "sans",
  },
  {
    component_id: "rsvp_card",
    section: "rsvp",
    name: "Card",
    preview_bg_color: "#ffffff",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "sans",
  },
  {
    component_id: "rsvp_minimal",
    section: "rsvp",
    name: "Minimal",
    preview_bg_color: "#ffffff",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "sans",
  },
  // registry
  {
    component_id: "registry_classic",
    section: "registry",
    name: "Classic",
    preview_bg_color: "#ffffff",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "sans",
  },
  {
    component_id: "registry_cards",
    section: "registry",
    name: "Cards",
    preview_bg_color: "#ffffff",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "sans",
  },
  {
    component_id: "registry_list",
    section: "registry",
    name: "List",
    preview_bg_color: "#ffffff",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "sans",
  },
  // timeline
  {
    component_id: "timeline_classic",
    section: "timeline",
    name: "Classic",
    preview_bg_color: "#fff8f5",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "serif",
  },
  {
    component_id: "timeline_vertical_line",
    section: "timeline",
    name: "Vertical Line",
    preview_bg_color: "#fff8f5",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "serif",
  },
  {
    component_id: "timeline_horizontal",
    section: "timeline",
    name: "Horizontal",
    preview_bg_color: "#fff8f5",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "serif",
  },
  // music
  {
    component_id: "music_classic",
    section: "music",
    name: "Classic",
    preview_bg_color: "#ffffff",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "sans",
  },
  {
    component_id: "music_playerbar",
    section: "music",
    name: "Player Bar",
    preview_bg_color: "#ffffff",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "sans",
  },
  {
    component_id: "music_minimal",
    section: "music",
    name: "Minimal",
    preview_bg_color: "#ffffff",
    preview_text_color: "#3a2e2e",
    preview_accent_color: "#c9a35c",
    font_style: "sans",
  },
];

export default {
  section_components: components.map((c) => ({ ...c, status: "active" })),
};
