export default {
  themes: [
    {
      theme_id: "sage",
      name: "Sage & Champagne",
      description: "Premium and romantic — works for almost every wedding style.",
      tokens: {
        background: "#f5ebdd",
        foreground: "#3b3b3b",
        card: "#fffdf9",
        cardForeground: "#3b3b3b",
        popover: "#fffdf9",
        popoverForeground: "#3b3b3b",
        primary: "#6f8f72",
        primaryForeground: "#fffdf9",
        secondary: "#ede1d1",
        secondaryForeground: "#3b3b3b",
        muted: "#ede1d1",
        mutedForeground: "#6b6b6b",
        accent: "#c9a86a",
        accentForeground: "#3b3b3b",
        border: "rgba(59, 59, 59, 0.12)",
        inputBackground: "#fffdf9",
        ring: "#6f8f72",
        sidebar: "#fffdf9",
        sidebarForeground: "#3b3b3b",
        sidebarPrimary: "#3f5c4a",
        sidebarPrimaryForeground: "#fffdf9",
        sidebarAccent: "#ede1d1",
        sidebarAccentForeground: "#3b3b3b",
        sidebarBorder: "rgba(59, 59, 59, 0.12)",
        sidebarRing: "#6f8f72",
      },
      is_active_web: true,
      is_active_couple: false,
      status: "active",
    },
    {
      theme_id: "rose",
      name: "Dusty Rose & Cream",
      description: "Very romantic but still elegant.",
      tokens: {
        background: "#fff8f2",
        foreground: "#4b3b34",
        card: "#f7e7e6",
        cardForeground: "#4b3b34",
        popover: "#fff8f2",
        popoverForeground: "#4b3b34",
        primary: "#d7a6a1",
        primaryForeground: "#fff8f2",
        secondary: "#f0dcd9",
        secondaryForeground: "#4b3b34",
        muted: "#f0dcd9",
        mutedForeground: "#8a7570",
        accent: "#a68b7c",
        accentForeground: "#fff8f2",
        border: "rgba(75, 59, 52, 0.12)",
        inputBackground: "#fff8f2",
        ring: "#d7a6a1",
        sidebar: "#f7e7e6",
        sidebarForeground: "#4b3b34",
        sidebarPrimary: "#4b3b34",
        sidebarPrimaryForeground: "#fff8f2",
        sidebarAccent: "#f0dcd9",
        sidebarAccentForeground: "#4b3b34",
        sidebarBorder: "rgba(75, 59, 52, 0.12)",
        sidebarRing: "#d7a6a1",
      },
      is_active_web: false,
      is_active_couple: true,
      status: "active",
    },
    {
      theme_id: "navy",
      name: "Navy & Gold",
      description: "Feels like a luxury hotel or high-end planner.",
      tokens: {
        background: "#ffffff",
        foreground: "#22262b",
        card: "#f5f5f5",
        cardForeground: "#22262b",
        popover: "#ffffff",
        popoverForeground: "#22262b",
        primary: "#223a5e",
        primaryForeground: "#ffffff",
        secondary: "#f5f5f5",
        secondaryForeground: "#22262b",
        muted: "#f5f5f5",
        mutedForeground: "#5b6472",
        accent: "#c7a96b",
        accentForeground: "#223a5e",
        border: "rgba(34, 58, 94, 0.14)",
        inputBackground: "#f5f5f5",
        ring: "#223a5e",
        sidebar: "#f5f5f5",
        sidebarForeground: "#22262b",
        sidebarPrimary: "#223a5e",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#eceef1",
        sidebarAccentForeground: "#223a5e",
        sidebarBorder: "rgba(34, 58, 94, 0.14)",
        sidebarRing: "#223a5e",
      },
      is_active_web: false,
      is_active_couple: false,
      status: "active",
    },
    {
      theme_id: "terracotta",
      name: "Terracotta & Sand",
      description: "Trendy, great for rustic and outdoor weddings.",
      tokens: {
        background: "#f3e8da",
        foreground: "#5a4636",
        card: "#f8efe3",
        cardForeground: "#5a4636",
        popover: "#f8efe3",
        popoverForeground: "#5a4636",
        primary: "#c56a4d",
        primaryForeground: "#f8efe3",
        secondary: "#ecdcc7",
        secondaryForeground: "#5a4636",
        muted: "#ecdcc7",
        mutedForeground: "#7d6a58",
        accent: "#79835c",
        accentForeground: "#f8efe3",
        border: "rgba(90, 70, 54, 0.14)",
        inputBackground: "#f8efe3",
        ring: "#c56a4d",
        sidebar: "#f8efe3",
        sidebarForeground: "#5a4636",
        sidebarPrimary: "#c56a4d",
        sidebarPrimaryForeground: "#f8efe3",
        sidebarAccent: "#ecdcc7",
        sidebarAccentForeground: "#5a4636",
        sidebarBorder: "rgba(90, 70, 54, 0.14)",
        sidebarRing: "#c56a4d",
      },
      is_active_web: false,
      is_active_couple: false,
      status: "active",
    },
  ],
};
